"""add_hierarchy_order_to_servers

Revision ID: 09449dfa185b
Revises: add_cms_fields_to_servers_table
Create Date: 2026-05-05 10:38:42.248453
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '09449dfa185b'
down_revision = 'add_cms_fields_to_servers_table'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favorite_meetings_uuid'), table_name='favorite_meetings')
    op.create_index(op.f('ix_favorite_meetings_UUID'), 'favorite_meetings', ['UUID'], unique=False)
    op.drop_index(op.f('ix_groups_uuid'), table_name='groups')
    op.drop_index(op.f('ix_meetings_uuid'), table_name='meetings')
    op.add_column('servers', sa.Column('hierarchy_order', sa.Integer(), nullable=False))
    op.alter_column('servers', 'port',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('servers', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('servers', 'is_primary',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('servers', 'connection_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    # Try to drop indexes that might not exist
    try:
        op.drop_index(op.f('ix_servers_connection_status'), table_name='servers')
    except:
        pass
    try:
        op.drop_index(op.f('ix_servers_is_active'), table_name='servers')
    except:
        pass
    try:
        op.drop_index(op.f('ix_servers_is_primary'), table_name='servers')
    except:
        pass
    try:
        op.drop_index(op.f('ix_servers_port'), table_name='servers')
    except:
        pass
    try:
        op.drop_index(op.f('ix_users_uuid'), table_name='users')
    except:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_uuid'), 'users', ['UUID'], unique=False)
    op.create_index(op.f('ix_servers_port'), 'servers', ['port'], unique=False)
    op.create_index(op.f('ix_servers_is_primary'), 'servers', ['is_primary'], unique=False)
    op.create_index(op.f('ix_servers_is_active'), 'servers', ['is_active'], unique=False)
    op.create_index(op.f('ix_servers_connection_status'), 'servers', ['connection_status'], unique=False)
    op.alter_column('servers', 'connection_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'disconnected'::character varying"),
               existing_nullable=False)
    op.alter_column('servers', 'is_primary',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('servers', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('servers', 'port',
               existing_type=sa.INTEGER(),
               server_default=sa.text('8443'),
               existing_nullable=False)
    op.drop_column('servers', 'hierarchy_order')
    op.create_index(op.f('ix_meetings_uuid'), 'meetings', ['UUID'], unique=False)
    op.create_index(op.f('ix_groups_uuid'), 'groups', ['UUID'], unique=False)
    op.drop_index(op.f('ix_favorite_meetings_UUID'), table_name='favorite_meetings')
    op.create_index(op.f('ix_favorite_meetings_uuid'), 'favorite_meetings', ['UUID'], unique=False)
    # ### end Alembic commands ###